# wrangler.toml
name = "pvnp-solutions"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-13"

[build]
command = "pnpm install && pnpm run build"
